/*
 * build-icons.mjs — turns assets/icons/*.svg into assets/icons.css.
 *
 * Each SVG becomes a CSS custom property holding the file inline as a data URI:
 *   --dz-icon-add: url("data:image/svg+xml,...");
 * Components draw an icon as a mask over currentColor — `mask: var(--dz-icon-add) center /
 * contain no-repeat` — so it takes their text color, and no component depends on the site
 * serving /assets at the root. The SVG files stay the single source; run this after adding
 * or changing one (`npm run icons`; `build` and `dev` run it first).
 *
 * icons.css is linked from index.html, so the properties sit on the page and inherit into
 * every component's shadow root. A host app can swap an icon by redefining one property.
 */
import { readdir, readFile, writeFile } from 'fs/promises';
import { join, dirname, basename } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const iconDir = join(root, 'assets', 'icons');
const outFile = join(root, 'assets', 'icons.css');
const NL = String.fromCharCode(10);

const files = (await readdir(iconDir)).filter(name => name.toLowerCase().endsWith('.svg')).sort();
const lines = [];
for (const file of files) {
    // Property names: lower case, anything outside a-z 0-9 becomes a hyphen.
    const name = basename(file, '.svg').toLowerCase().split('').map(ch => (/[a-z0-9]/.test(ch) ? ch : '-')).join('');
    // Collapse whitespace so the data URI stays compact; encodeURIComponent makes it safe
    // inside url("...") (quotes, #, < and > are all encoded).
    const svg = (await readFile(join(iconDir, file), 'utf8')).split(NL).map(line => line.trim()).join(' ').trim();
    lines.push('    --dz-icon-' + name + ': url("data:image/svg+xml,' + encodeURIComponent(svg) + '");');
}

const css = [
    '/*',
    ' * icons.css - GENERATED by scripts/build-icons.mjs from assets/icons/*.svg. Do not edit;',
    ' * change the SVG and run `npm run icons`. One custom property per icon, used by components',
    ' * as a mask: mask: var(--dz-icon-<name>) center / contain no-repeat.',
    ' */',
    ':root {',
    ...lines,
    '}',
    ''
].join(NL);

await writeFile(outFile, css, 'utf8');
console.log('icons.css: ' + files.length + ' icons (' + files.map(f => basename(f, '.svg')).join(', ') + ')');
